### ISSUE TITLE
seq without element type 

### ISSUE THREAD

**Issue by bung87** [SciNim/numericalnim#29]
https://github.com/SciNim/numericalnim/blob/614cb304d74ac32869ff74e0d013681ecf4ff5c8/src/numericalnim/integrate.nim#L420  

if this https://github.com/nim-lang/Nim/pull/20412 get merged, it will be a problem.

**Comment by HugoGranstrom** [comment]
I'm as baffled as you to why I wrote it like that to begin with :sweat_smile: 

Do I have to make a new release for the CI to work on your end now?

**Comment by bung87** [comment]
not sure, but better bump a new release, nimble will use latest release tag.

**Comment by HugoGranstrom** [comment]
Done
